<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * Autogenerated CRUD-like access library for Vtiger Database Tables
 *
 * GNU General Public Licence v3
 * Copyright (C) 2012 Carlos Paparoni
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   VtigerPhplistIntegration
 * @package    VtigerDBCRUDLibrary
 * @author     Carlos Paparoni <carlos.paparoni@gmail.com>
 * @copyright  (C) 2012 Carlos Paparoni
 * @license    http://www.gnu.org/licenses/gpl.html GNU General Public Licence v3
 * @version    1.0
 * @link       http://d1m1.heliohost.org/code/php/vtiger-access-library
 */


/**
 * 
 *
 * @version 1.107
 * @package entity
 */
class VTigerCurrencyInfo extends Db2PhpEntityBase implements Db2PhpEntityModificationTracking {
	private static $CLASS_NAME='VTigerCurrencyInfo';
	const SQL_IDENTIFIER_QUOTE='`';
	const SQL_TABLE_NAME='vtiger_currency_info';
	const SQL_INSERT='INSERT INTO `vtiger_currency_info` (`id`,`currency_name`,`currency_code`,`currency_symbol`,`conversion_rate`,`currency_status`,`defaultid`,`deleted`) VALUES (?,?,?,?,?,?,?,?)';
	const SQL_INSERT_AUTOINCREMENT='INSERT INTO `vtiger_currency_info` (`currency_name`,`currency_code`,`currency_symbol`,`conversion_rate`,`currency_status`,`defaultid`,`deleted`) VALUES (?,?,?,?,?,?,?)';
	const SQL_UPDATE='UPDATE `vtiger_currency_info` SET `id`=?,`currency_name`=?,`currency_code`=?,`currency_symbol`=?,`conversion_rate`=?,`currency_status`=?,`defaultid`=?,`deleted`=? WHERE `id`=?';
	const SQL_SELECT_PK='SELECT * FROM `vtiger_currency_info` WHERE `id`=?';
	const SQL_DELETE_PK='DELETE FROM `vtiger_currency_info` WHERE `id`=?';
	const FIELD_ID=-923619421;
	const FIELD_CURRENCY_NAME=1324260977;
	const FIELD_CURRENCY_CODE=1323946451;
	const FIELD_CURRENCY_SYMBOL=1469790206;
	const FIELD_CONVERSION_RATE=1290549473;
	const FIELD_CURRENCY_STATUS=1464832600;
	const FIELD_DEFAULTID=-146125932;
	const FIELD_DELETED=-1277173103;
	private static $PRIMARY_KEYS=array(self::FIELD_ID);
	private static $AUTOINCREMENT_FIELDS=array(self::FIELD_ID);
	private static $FIELD_NAMES=array(
		self::FIELD_ID=>'id',
		self::FIELD_CURRENCY_NAME=>'currency_name',
		self::FIELD_CURRENCY_CODE=>'currency_code',
		self::FIELD_CURRENCY_SYMBOL=>'currency_symbol',
		self::FIELD_CONVERSION_RATE=>'conversion_rate',
		self::FIELD_CURRENCY_STATUS=>'currency_status',
		self::FIELD_DEFAULTID=>'defaultid',
		self::FIELD_DELETED=>'deleted');
	private static $PROPERTY_NAMES=array(
		self::FIELD_ID=>'id',
		self::FIELD_CURRENCY_NAME=>'currencyName',
		self::FIELD_CURRENCY_CODE=>'currencyCode',
		self::FIELD_CURRENCY_SYMBOL=>'currencySymbol',
		self::FIELD_CONVERSION_RATE=>'conversionRate',
		self::FIELD_CURRENCY_STATUS=>'currencyStatus',
		self::FIELD_DEFAULTID=>'defaultId',
		self::FIELD_DELETED=>'deleted');
	private static $PROPERTY_TYPES=array(
		self::FIELD_ID=>Db2PhpEntity::PHP_TYPE_INT,
		self::FIELD_CURRENCY_NAME=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_CURRENCY_CODE=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_CURRENCY_SYMBOL=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_CONVERSION_RATE=>Db2PhpEntity::PHP_TYPE_FLOAT,
		self::FIELD_CURRENCY_STATUS=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_DEFAULTID=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_DELETED=>Db2PhpEntity::PHP_TYPE_INT);
	private static $FIELD_TYPES=array(
		self::FIELD_ID=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,false),
		self::FIELD_CURRENCY_NAME=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,100,0,true),
		self::FIELD_CURRENCY_CODE=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,100,0,true),
		self::FIELD_CURRENCY_SYMBOL=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,30,0,true),
		self::FIELD_CONVERSION_RATE=>array(Db2PhpEntity::JDBC_TYPE_DECIMAL,10,3,true),
		self::FIELD_CURRENCY_STATUS=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,25,0,true),
		self::FIELD_DEFAULTID=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,10,0,false),
		self::FIELD_DELETED=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,false));
	private static $DEFAULT_VALUES=array(
		self::FIELD_ID=>null,
		self::FIELD_CURRENCY_NAME=>null,
		self::FIELD_CURRENCY_CODE=>null,
		self::FIELD_CURRENCY_SYMBOL=>null,
		self::FIELD_CONVERSION_RATE=>null,
		self::FIELD_CURRENCY_STATUS=>null,
		self::FIELD_DEFAULTID=>'0',
		self::FIELD_DELETED=>0);
	private $id;
	private $currencyName;
	private $currencyCode;
	private $currencySymbol;
	private $conversionRate;
	private $currencyStatus;
	private $defaultId;
	private $deleted;

	/**
	 * set value for id 
	 *
	 * type:INT,size:10,default:null,primary,unique,autoincrement
	 *
	 * @param mixed $id
	 * @return VTigerCurrencyInfo
	 */
	public function &setId($id) {
		$this->notifyChanged(self::FIELD_ID,$this->id,$id);
		$this->id=$id;
		return $this;
	}

	/**
	 * get value for id 
	 *
	 * type:INT,size:10,default:null,primary,unique,autoincrement
	 *
	 * @return mixed
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * set value for currency_name 
	 *
	 * type:VARCHAR,size:100,default:null,nullable
	 *
	 * @param mixed $currencyName
	 * @return VTigerCurrencyInfo
	 */
	public function &setCurrencyName($currencyName) {
		$this->notifyChanged(self::FIELD_CURRENCY_NAME,$this->currencyName,$currencyName);
		$this->currencyName=$currencyName;
		return $this;
	}

	/**
	 * get value for currency_name 
	 *
	 * type:VARCHAR,size:100,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getCurrencyName() {
		return $this->currencyName;
	}

	/**
	 * set value for currency_code 
	 *
	 * type:VARCHAR,size:100,default:null,nullable
	 *
	 * @param mixed $currencyCode
	 * @return VTigerCurrencyInfo
	 */
	public function &setCurrencyCode($currencyCode) {
		$this->notifyChanged(self::FIELD_CURRENCY_CODE,$this->currencyCode,$currencyCode);
		$this->currencyCode=$currencyCode;
		return $this;
	}

	/**
	 * get value for currency_code 
	 *
	 * type:VARCHAR,size:100,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getCurrencyCode() {
		return $this->currencyCode;
	}

	/**
	 * set value for currency_symbol 
	 *
	 * type:VARCHAR,size:30,default:null,nullable
	 *
	 * @param mixed $currencySymbol
	 * @return VTigerCurrencyInfo
	 */
	public function &setCurrencySymbol($currencySymbol) {
		$this->notifyChanged(self::FIELD_CURRENCY_SYMBOL,$this->currencySymbol,$currencySymbol);
		$this->currencySymbol=$currencySymbol;
		return $this;
	}

	/**
	 * get value for currency_symbol 
	 *
	 * type:VARCHAR,size:30,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getCurrencySymbol() {
		return $this->currencySymbol;
	}

	/**
	 * set value for conversion_rate 
	 *
	 * type:DECIMAL,size:10,default:null,nullable
	 *
	 * @param mixed $conversionRate
	 * @return VTigerCurrencyInfo
	 */
	public function &setConversionRate($conversionRate) {
		$this->notifyChanged(self::FIELD_CONVERSION_RATE,$this->conversionRate,$conversionRate);
		$this->conversionRate=$conversionRate;
		return $this;
	}

	/**
	 * get value for conversion_rate 
	 *
	 * type:DECIMAL,size:10,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getConversionRate() {
		return $this->conversionRate;
	}

	/**
	 * set value for currency_status 
	 *
	 * type:VARCHAR,size:25,default:null,nullable
	 *
	 * @param mixed $currencyStatus
	 * @return VTigerCurrencyInfo
	 */
	public function &setCurrencyStatus($currencyStatus) {
		$this->notifyChanged(self::FIELD_CURRENCY_STATUS,$this->currencyStatus,$currencyStatus);
		$this->currencyStatus=$currencyStatus;
		return $this;
	}

	/**
	 * get value for currency_status 
	 *
	 * type:VARCHAR,size:25,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getCurrencyStatus() {
		return $this->currencyStatus;
	}

	/**
	 * set value for defaultid 
	 *
	 * type:VARCHAR,size:10,default:0
	 *
	 * @param mixed $defaultId
	 * @return VTigerCurrencyInfo
	 */
	public function &setDefaultId($defaultId) {
		$this->notifyChanged(self::FIELD_DEFAULTID,$this->defaultId,$defaultId);
		$this->defaultId=$defaultId;
		return $this;
	}

	/**
	 * get value for defaultid 
	 *
	 * type:VARCHAR,size:10,default:0
	 *
	 * @return mixed
	 */
	public function getDefaultId() {
		return $this->defaultId;
	}

	/**
	 * set value for deleted 
	 *
	 * type:INT,size:10,default:0
	 *
	 * @param mixed $deleted
	 * @return VTigerCurrencyInfo
	 */
	public function &setDeleted($deleted) {
		$this->notifyChanged(self::FIELD_DELETED,$this->deleted,$deleted);
		$this->deleted=$deleted;
		return $this;
	}

	/**
	 * get value for deleted 
	 *
	 * type:INT,size:10,default:0
	 *
	 * @return mixed
	 */
	public function getDeleted() {
		return $this->deleted;
	}

	/**
	 * Get table name
	 *
	 * @return string
	 */
	public static function getTableName() {
		return self::SQL_TABLE_NAME;
	}

	/**
	 * Get array with field id as index and field name as value
	 *
	 * @return array
	 */
	public static function getFieldNames() {
		return self::$FIELD_NAMES;
	}

	/**
	 * Get array with field id as index and property name as value
	 *
	 * @return array
	 */
	public static function getPropertyNames() {
		return self::$PROPERTY_NAMES;
	}

	/**
	 * get the field name for the passed field id.
	 *
	 * @param int $fieldId
	 * @param bool $fullyQualifiedName true if field name should be qualified by table name
	 * @return string field name for the passed field id, null if the field doesn't exist
	 */
	public static function getFieldNameByFieldId($fieldId, $fullyQualifiedName=true) {
		if (!array_key_exists($fieldId, self::$FIELD_NAMES)) {
			return null;
		}
		$fieldName=self::SQL_IDENTIFIER_QUOTE . self::$FIELD_NAMES[$fieldId] . self::SQL_IDENTIFIER_QUOTE;
		if ($fullyQualifiedName) {
			return self::SQL_IDENTIFIER_QUOTE . self::SQL_TABLE_NAME . self::SQL_IDENTIFIER_QUOTE . '.' . $fieldName;
		}
		return $fieldName;
	}

	/**
	 * Get array with field ids of identifiers
	 *
	 * @return array
	 */
	public static function getIdentifierFields() {
		return self::$PRIMARY_KEYS;
	}

	/**
	 * Get array with field ids of autoincrement fields
	 *
	 * @return array
	 */
	public static function getAutoincrementFields() {
		return self::$AUTOINCREMENT_FIELDS;
	}

	/**
	 * Get array with field id as index and property type as value
	 *
	 * @return array
	 */
	public static function getPropertyTypes() {
		return self::$PROPERTY_TYPES;
	}

	/**
	 * Get array with field id as index and field type as value
	 *
	 * @return array
	 */
	public static function getFieldTypes() {
		return self::$FIELD_TYPES;
	}

	/**
	 * Assign default values according to table
	 * 
	 */
	public function assignDefaultValues() {
		$this->assignByArray(self::$DEFAULT_VALUES);
	}


	/**
	 * return hash with the field name as index and the field value as value.
	 *
	 * @return array
	 */
	public function toHash() {
		$array=$this->toArray();
		$hash=array();
		foreach ($array as $fieldId=>$value) {
			$hash[self::$FIELD_NAMES[$fieldId]]=$value;
		}
		return $hash;
	}

	/**
	 * return array with the field id as index and the field value as value.
	 *
	 * @return array
	 */
	public function toArray() {
		return array(
			self::FIELD_ID=>$this->getId(),
			self::FIELD_CURRENCY_NAME=>$this->getCurrencyName(),
			self::FIELD_CURRENCY_CODE=>$this->getCurrencyCode(),
			self::FIELD_CURRENCY_SYMBOL=>$this->getCurrencySymbol(),
			self::FIELD_CONVERSION_RATE=>$this->getConversionRate(),
			self::FIELD_CURRENCY_STATUS=>$this->getCurrencyStatus(),
			self::FIELD_DEFAULTID=>$this->getDefaultId(),
			self::FIELD_DELETED=>$this->getDeleted());
	}


	/**
	 * return array with the field id as index and the field value as value for the identifier fields.
	 *
	 * @return array
	 */
	public function getPrimaryKeyValues() {
		return array(
			self::FIELD_ID=>$this->getId());
	}

	/**
	 * cached statements
	 *
	 * @var array<string,array<string,PDOStatement>>
	 */
	private static $stmts=array();
	private static $cacheStatements=true;
	
	/**
	 * prepare passed string as statement or return cached if enabled and available
	 *
	 * @param PDO $db
	 * @param string $statement
	 * @return PDOStatement
	 */
	protected static function prepareStatement(PDO $db, $statement) {
		if(self::isCacheStatements()) {
			if (in_array($statement, array(self::SQL_INSERT, self::SQL_INSERT_AUTOINCREMENT, self::SQL_UPDATE, self::SQL_SELECT_PK, self::SQL_DELETE_PK))) {
				$dbInstanceId=spl_object_hash($db);
				if (empty(self::$stmts[$statement][$dbInstanceId])) {
					self::$stmts[$statement][$dbInstanceId]=$db->prepare($statement);
				}
				return self::$stmts[$statement][$dbInstanceId];
			}
		}
		return $db->prepare($statement);
	}

	/**
	 * Enable statement cache
	 *
	 * @param bool $cache
	 */
	public static function setCacheStatements($cache) {
		self::$cacheStatements=true==$cache;
	}

	/**
	 * Check if statement cache is enabled
	 *
	 * @return bool
	 */
	public static function isCacheStatements() {
		return self::$cacheStatements;
	}
	
	/**
	 * check if this instance exists in the database
	 *
	 * @param PDO $db
	 * @return bool
	 */
	public function existsInDatabase(PDO $db) {
		$filter=array();
		foreach ($this->getPrimaryKeyValues() as $fieldId=>$value) {
			$filter[]=new DFC($fieldId, $value, DFC::EXACT_NULLSAFE);
		}
		return 0!=count(self::findByFilter($db, $filter, true));
	}
	
	/**
	 * Update to database if exists, otherwise insert
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function updateInsertToDatabase(PDO $db) {
		if ($this->existsInDatabase($db)) {
			return $this->updateToDatabase($db);
		} else {
			return $this->insertIntoDatabase($db);
		}
	}

	/**
	 * Query by Example.
	 *
	 * Match by attributes of passed example instance and return matched rows as an array of VTigerCurrencyInfo instances
	 *
	 * @param PDO $db a PDO Database instance
	 * @param VTigerCurrencyInfo $example an example instance defining the conditions. All non-null properties will be considered a constraint, null values will be ignored.
	 * @param boolean $and true if conditions should be and'ed, false if they should be or'ed
	 * @param array $sort array of DSC instances
	 * @return VTigerCurrencyInfo[]
	 */
	public static function findByExample(PDO $db,VTigerCurrencyInfo $example, $and=true, $sort=null) {
		$exampleValues=$example->toArray();
		$filter=array();
		foreach ($exampleValues as $fieldId=>$value) {
			if (null!==$value) {
				$filter[$fieldId]=$value;
			}
		}
		return self::findByFilter($db, $filter, $and, $sort);
	}

	/**
	 * Query by filter.
	 *
	 * The filter can be either an hash with the field id as index and the value as filter value,
	 * or a array of DFC instances.
	 *
	 * Will return matched rows as an array of VTigerCurrencyInfo instances.
	 *
	 * @param PDO $db a PDO Database instance
	 * @param array $filter array of DFC instances defining the conditions
	 * @param boolean $and true if conditions should be and'ed, false if they should be or'ed
	 * @param array $sort array of DSC instances
	 * @return VTigerCurrencyInfo[]
	 */
	public static function findByFilter(PDO $db, $filter, $and=true, $sort=null) {
		if (!($filter instanceof DFCInterface)) {
			$filter=new DFCAggregate($filter, $and);
		}
		$sql='SELECT * FROM `vtiger_currency_info`'
		. self::buildSqlWhere($filter, $and, false, true)
		. self::buildSqlOrderBy($sort);

		$stmt=self::prepareStatement($db, $sql);
		self::bindValuesForFilter($stmt, $filter);
		return self::fromStatement($stmt);
	}

	/**
	 * Will execute the passed statement and return the result as an array of VTigerCurrencyInfo instances
	 *
	 * @param PDOStatement $stmt
	 * @return VTigerCurrencyInfo[]
	 */
	public static function fromStatement(PDOStatement $stmt) {
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		return self::fromExecutedStatement($stmt);
	}

	/**
	 * returns the result as an array of VTigerCurrencyInfo instances without executing the passed statement
	 *
	 * @param PDOStatement $stmt
	 * @return VTigerCurrencyInfo[]
	 */
	public static function fromExecutedStatement(PDOStatement $stmt) {
		$resultInstances=array();
		while($result=$stmt->fetch(PDO::FETCH_ASSOC)) {
			$o=new VTigerCurrencyInfo();
			$o->assignByHash($result);
			$o->notifyPristine();
			$resultInstances[]=$o;
		}
		$stmt->closeCursor();
		return $resultInstances;
	}

	/**
	 * Get sql WHERE part from filter.
	 *
	 * @param array $filter
	 * @param bool $and
	 * @param bool $fullyQualifiedNames true if field names should be qualified by table name
	 * @param bool $prependWhere true if WHERE should be prepended to conditions
	 * @return string
	 */
	public static function buildSqlWhere($filter, $and, $fullyQualifiedNames=true, $prependWhere=false) {
		if (!($filter instanceof DFCInterface)) {
			$filter=new DFCAggregate($filter, $and);
		}
		return $filter->buildSqlWhere(new self::$CLASS_NAME, $fullyQualifiedNames, $prependWhere);
	}

	/**
	 * get sql ORDER BY part from DSCs
	 *
	 * @param array $sort array of DSC instances
	 * @return string
	 */
	protected static function buildSqlOrderBy($sort) {
		return DSC::buildSqlOrderBy(new self::$CLASS_NAME, $sort);
	}

	/**
	 * bind values from filter to statement
	 *
	 * @param PDOStatement $stmt
	 * @param DFCInterface $filter
	 */
	public static function bindValuesForFilter(PDOStatement &$stmt, DFCInterface $filter) {
		$filter->bindValuesForFilter(new self::$CLASS_NAME, $stmt);
	}

	/**
	 * Execute select query and return matched rows as an array of VTigerCurrencyInfo instances.
	 *
	 * The query should of course be on the table for this entity class and return all fields.
	 *
	 * @param PDO $db a PDO Database instance
	 * @param string $sql
	 * @return VTigerCurrencyInfo[]
	 */
	public static function findBySql(PDO $db, $sql) {
		$stmt=$db->query($sql);
		return self::fromExecutedStatement($stmt);
	}

	/**
	 * Delete rows matching the filter
	 *
	 * The filter can be either an hash with the field id as index and the value as filter value,
	 * or a array of DFC instances.
	 *
	 * @param PDO $db
	 * @param array $filter
	 * @param bool $and
	 * @return mixed
	 */
	public static function deleteByFilter(PDO $db, $filter, $and=true) {
		if (!($filter instanceof DFCInterface)) {
			$filter=new DFCAggregate($filter, $and);
		}
		if (0==count($filter)) {
			throw new InvalidArgumentException('refusing to delete without filter'); // just comment out this line if you are brave
		}
		$sql='DELETE FROM `vtiger_currency_info`'
		. self::buildSqlWhere($filter, $and, false, true);
		$stmt=self::prepareStatement($db, $sql);
		self::bindValuesForFilter($stmt, $filter);
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		return $affected;
	}

	/**
	 * Assign values from array with the field id as index and the value as value
	 *
	 * @param array $array
	 */
	public function assignByArray($array) {
		$result=array();
		foreach ($array as $fieldId=>$value) {
			$result[self::$FIELD_NAMES[$fieldId]]=$value;
		}
		$this->assignByHash($result);
	}

	/**
	 * Assign values from hash where the indexes match the tables field names
	 *
	 * @param array $result
	 */
	public function assignByHash($result) {
		$this->setId($result['id']);
		$this->setCurrencyName($result['currency_name']);
		$this->setCurrencyCode($result['currency_code']);
		$this->setCurrencySymbol($result['currency_symbol']);
		$this->setConversionRate($result['conversion_rate']);
		$this->setCurrencyStatus($result['currency_status']);
		$this->setDefaultId($result['defaultid']);
		$this->setDeleted($result['deleted']);
	}

	/**
	 * Get element instance by it's primary key(s).
	 * Will return null if no row was matched.
	 *
	 * @param PDO $db
	 * @return VTigerCurrencyInfo
	 */
	public static function findById(PDO $db,$id) {
		$stmt=self::prepareStatement($db,self::SQL_SELECT_PK);
		$stmt->bindValue(1,$id);
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$result=$stmt->fetch(PDO::FETCH_ASSOC);
		$stmt->closeCursor();
		if(!$result) {
			return null;
		}
		$o=new VTigerCurrencyInfo();
		$o->assignByHash($result);
		$o->notifyPristine();
		return $o;
	}

	/**
	 * Bind all values to statement
	 *
	 * @param PDOStatement $stmt
	 */
	protected function bindValues(PDOStatement &$stmt) {
		$stmt->bindValue(1,$this->getId());
		$stmt->bindValue(2,$this->getCurrencyName());
		$stmt->bindValue(3,$this->getCurrencyCode());
		$stmt->bindValue(4,$this->getCurrencySymbol());
		$stmt->bindValue(5,$this->getConversionRate());
		$stmt->bindValue(6,$this->getCurrencyStatus());
		$stmt->bindValue(7,$this->getDefaultId());
		$stmt->bindValue(8,$this->getDeleted());
	}


	/**
	 * Insert this instance into the database
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function insertIntoDatabase(PDO $db) {
		if (null===$this->getId()) {
			$stmt=self::prepareStatement($db,self::SQL_INSERT_AUTOINCREMENT);
			$stmt->bindValue(1,$this->getCurrencyName());
			$stmt->bindValue(2,$this->getCurrencyCode());
			$stmt->bindValue(3,$this->getCurrencySymbol());
			$stmt->bindValue(4,$this->getConversionRate());
			$stmt->bindValue(5,$this->getCurrencyStatus());
			$stmt->bindValue(6,$this->getDefaultId());
			$stmt->bindValue(7,$this->getDeleted());
		} else {
			$stmt=self::prepareStatement($db,self::SQL_INSERT);
			$this->bindValues($stmt);
		}
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$lastInsertId=$db->lastInsertId();
		if (false!==$lastInsertId) {
			$this->setId($lastInsertId);
		}
		$stmt->closeCursor();
		$this->notifyPristine();
		return $affected;
	}


	/**
	 * Update this instance into the database
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function updateToDatabase(PDO $db) {
		$stmt=self::prepareStatement($db,self::SQL_UPDATE);
		$this->bindValues($stmt);
		$stmt->bindValue(9,$this->getId());
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		$this->notifyPristine();
		return $affected;
	}


	/**
	 * Delete this instance from the database
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function deleteFromDatabase(PDO $db) {
		$stmt=self::prepareStatement($db,self::SQL_DELETE_PK);
		$stmt->bindValue(1,$this->getId());
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		return $affected;
	}

	/**
	 * return array with the property name as index and the field value as value.
	 * ezComponents support method
	 *
	 * @return array
	 */
	public function getState() {
		$array=$this->toArray();
		$state=array();
		foreach ($array as $fieldId=>$value) {
			$state[self::$PROPERTY_NAMES[$fieldId]]=$value;
		}
		return $state;
	}

	/**
	 * Assign values from hash where the indexes match the property names.
	 * ezComponents support method
	 *
	 * @param array $state
	 */
	public function setState(array $state) {
		$propertyNameToFieldId=array_flip(self::$PROPERTY_NAMES);
		$hash=$this->toHash();
		foreach ($state as $propertyName=>$value) {
			$hash[self::$FIELD_NAMES[$propertyNameToFieldId[$propertyName]]]=$value;
		}
		$this->assignByHash($hash);
	}

	/**
	 * get persistence definition for ezComponents
	 *
	 * @return ezcPersistentObjectDefinition
	 */
	public static function toEzcPersistentObjectDefinition() {
		static $typeMapping=array(
			Db2PhpEntity::PHP_TYPE_BOOL=>ezcPersistentObjectProperty::PHP_TYPE_BOOL,
			Db2PhpEntity::PHP_TYPE_INT=>ezcPersistentObjectProperty::PHP_TYPE_INT,
			Db2PhpEntity::PHP_TYPE_FLOAT=>ezcPersistentObjectProperty::PHP_TYPE_FLOAT,
			Db2PhpEntity::PHP_TYPE_STRING=>ezcPersistentObjectProperty::PHP_TYPE_STRING
		);
		$def=new ezcPersistentObjectDefinition();
		$def->table=self::SQL_TABLE_NAME;
		$def->class='VTigerCurrencyInfo';
		if (!empty (self::$PRIMARY_KEYS)) {
			$pkField=self::$PRIMARY_KEYS[0];
			$def->idProperty=new ezcPersistentObjectIdProperty();
			$def->idProperty->columnName=self::$FIELD_NAMES[$pkField];
			$def->idProperty->propertyName=self::$PROPERTY_NAMES[$pkField];
			$def->idProperty->generator=new ezcPersistentGeneratorDefinition(
				in_array($pkField, self::$AUTOINCREMENT_FIELDS) ? 'ezcPersistentNativeGenerator' : 'ezcPersistentManualGenerator');
		} else {
			$pkField=null;
		}
		foreach (self::$PROPERTY_NAMES as $fieldId=>$propertyName) {
			if ($fieldId!==$pkField) {
				$def->properties[$propertyName]=new ezcPersistentObjectProperty();
				$def->properties[$propertyName]->columnName=self::$FIELD_NAMES[$fieldId];
				$def->properties[$propertyName]->propertyName=$propertyName;
				$def->properties[$propertyName]->propertyType=$typeMapping[self::$PROPERTY_TYPES[$fieldId]];
			}
		}
		return $def;
	}


	/**
	 * get element as DOM Document
	 *
	 * @return DOMDocument
	 */
	public function toDOM() {
		return self::hashToDomDocument($this->toHash(), 'VTigerCurrencyInfo');
	}

	/**
	 * get single VTigerCurrencyInfo instance from a DOMElement
	 *
	 * @param DOMElement $node
	 * @return VTigerCurrencyInfo
	 */
	public static function fromDOMElement(DOMElement $node) {
		$o=new VTigerCurrencyInfo();
		$o->assignByHash(self::domNodeToHash($node, self::$FIELD_NAMES, self::$DEFAULT_VALUES, self::$FIELD_TYPES));
			$o->notifyPristine();
		return $o;
	}

	/**
	 * get all instances of VTigerCurrencyInfo from the passed DOMDocument
	 *
	 * @param DOMDocument $doc
	 * @return VTigerCurrencyInfo[]
	 */
	public static function fromDOMDocument(DOMDocument $doc) {
		$instances=array();
		foreach ($doc->getElementsByTagName('VTigerCurrencyInfo') as $node) {
			$instances[]=self::fromDOMElement($node);
		}
		return $instances;
	}

}
?>