<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * Autogenerated CRUD-like access library for Vtiger Database Tables
 *
 * GNU General Public Licence v3
 * Copyright (C) 2012 Carlos Paparoni
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   VtigerPhplistIntegration
 * @package    VtigerDBCRUDLibrary
 * @author     Carlos Paparoni <carlos.paparoni@gmail.com>
 * @copyright  (C) 2012 Carlos Paparoni
 * @license    http://www.gnu.org/licenses/gpl.html GNU General Public Licence v3
 * @version    1.0
 * @link       http://d1m1.heliohost.org/code/php/vtiger-access-library
 */


/**
 * 
 *
 * @version 1.107
 * @package entity
 */
class VTigerNotes extends Db2PhpEntityBase implements Db2PhpEntityModificationTracking {
	private static $CLASS_NAME='VTigerNotes';
	const SQL_IDENTIFIER_QUOTE='`';
	const SQL_TABLE_NAME='vtiger_notes';
	const SQL_INSERT='INSERT INTO `vtiger_notes` (`notesid`,`note_no`,`title`,`filename`,`notecontent`,`folderid`,`filetype`,`filelocationtype`,`filedownloadcount`,`filestatus`,`filesize`,`fileversion`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)';
	const SQL_INSERT_AUTOINCREMENT='INSERT INTO `vtiger_notes` (`notesid`,`note_no`,`title`,`filename`,`notecontent`,`folderid`,`filetype`,`filelocationtype`,`filedownloadcount`,`filestatus`,`filesize`,`fileversion`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)';
	const SQL_UPDATE='UPDATE `vtiger_notes` SET `notesid`=?,`note_no`=?,`title`=?,`filename`=?,`notecontent`=?,`folderid`=?,`filetype`=?,`filelocationtype`=?,`filedownloadcount`=?,`filestatus`=?,`filesize`=?,`fileversion`=? WHERE `notesid`=?';
	const SQL_SELECT_PK='SELECT * FROM `vtiger_notes` WHERE `notesid`=?';
	const SQL_DELETE_PK='DELETE FROM `vtiger_notes` WHERE `notesid`=?';
	const FIELD_NOTESID=1284937145;
	const FIELD_NOTE_NO=1284918091;
	const FIELD_TITLE=730721205;
	const FIELD_FILENAME=-1138479222;
	const FIELD_NOTECONTENT=202350564;
	const FIELD_FOLDERID=-109599860;
	const FIELD_FILETYPE=-1138277319;
	const FIELD_FILELOCATIONTYPE=-1766026642;
	const FIELD_FILEDOWNLOADCOUNT=-1394731160;
	const FIELD_FILESTATUS=1298481457;
	const FIELD_FILESIZE=-1138322176;
	const FIELD_FILEVERSION=-448015495;
	private static $PRIMARY_KEYS=array(self::FIELD_NOTESID);
	private static $AUTOINCREMENT_FIELDS=array();
	private static $FIELD_NAMES=array(
		self::FIELD_NOTESID=>'notesid',
		self::FIELD_NOTE_NO=>'note_no',
		self::FIELD_TITLE=>'title',
		self::FIELD_FILENAME=>'filename',
		self::FIELD_NOTECONTENT=>'notecontent',
		self::FIELD_FOLDERID=>'folderid',
		self::FIELD_FILETYPE=>'filetype',
		self::FIELD_FILELOCATIONTYPE=>'filelocationtype',
		self::FIELD_FILEDOWNLOADCOUNT=>'filedownloadcount',
		self::FIELD_FILESTATUS=>'filestatus',
		self::FIELD_FILESIZE=>'filesize',
		self::FIELD_FILEVERSION=>'fileversion');
	private static $PROPERTY_NAMES=array(
		self::FIELD_NOTESID=>'notesId',
		self::FIELD_NOTE_NO=>'noteNo',
		self::FIELD_TITLE=>'title',
		self::FIELD_FILENAME=>'fileName',
		self::FIELD_NOTECONTENT=>'noteContent',
		self::FIELD_FOLDERID=>'folderId',
		self::FIELD_FILETYPE=>'fileType',
		self::FIELD_FILELOCATIONTYPE=>'fileLocationType',
		self::FIELD_FILEDOWNLOADCOUNT=>'fileDownloadCount',
		self::FIELD_FILESTATUS=>'fileStatus',
		self::FIELD_FILESIZE=>'filesIze',
		self::FIELD_FILEVERSION=>'fileVersion');
	private static $PROPERTY_TYPES=array(
		self::FIELD_NOTESID=>Db2PhpEntity::PHP_TYPE_INT,
		self::FIELD_NOTE_NO=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_TITLE=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_FILENAME=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_NOTECONTENT=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_FOLDERID=>Db2PhpEntity::PHP_TYPE_INT,
		self::FIELD_FILETYPE=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_FILELOCATIONTYPE=>Db2PhpEntity::PHP_TYPE_STRING,
		self::FIELD_FILEDOWNLOADCOUNT=>Db2PhpEntity::PHP_TYPE_INT,
		self::FIELD_FILESTATUS=>Db2PhpEntity::PHP_TYPE_INT,
		self::FIELD_FILESIZE=>Db2PhpEntity::PHP_TYPE_INT,
		self::FIELD_FILEVERSION=>Db2PhpEntity::PHP_TYPE_STRING);
	private static $FIELD_TYPES=array(
		self::FIELD_NOTESID=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,false),
		self::FIELD_NOTE_NO=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,100,0,false),
		self::FIELD_TITLE=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,50,0,false),
		self::FIELD_FILENAME=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,200,0,true),
		self::FIELD_NOTECONTENT=>array(Db2PhpEntity::JDBC_TYPE_LONGVARCHAR,65535,0,true),
		self::FIELD_FOLDERID=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,false),
		self::FIELD_FILETYPE=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,50,0,true),
		self::FIELD_FILELOCATIONTYPE=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,5,0,true),
		self::FIELD_FILEDOWNLOADCOUNT=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,true),
		self::FIELD_FILESTATUS=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,true),
		self::FIELD_FILESIZE=>array(Db2PhpEntity::JDBC_TYPE_INTEGER,10,0,false),
		self::FIELD_FILEVERSION=>array(Db2PhpEntity::JDBC_TYPE_VARCHAR,50,0,true));
	private static $DEFAULT_VALUES=array(
		self::FIELD_NOTESID=>0,
		self::FIELD_NOTE_NO=>'',
		self::FIELD_TITLE=>'',
		self::FIELD_FILENAME=>null,
		self::FIELD_NOTECONTENT=>null,
		self::FIELD_FOLDERID=>1,
		self::FIELD_FILETYPE=>null,
		self::FIELD_FILELOCATIONTYPE=>null,
		self::FIELD_FILEDOWNLOADCOUNT=>null,
		self::FIELD_FILESTATUS=>null,
		self::FIELD_FILESIZE=>0,
		self::FIELD_FILEVERSION=>null);
	private $notesId;
	private $noteNo;
	private $title;
	private $fileName;
	private $noteContent;
	private $folderId;
	private $fileType;
	private $fileLocationType;
	private $fileDownloadCount;
	private $fileStatus;
	private $filesIze;
	private $fileVersion;

	/**
	 * set value for notesid 
	 *
	 * type:INT,size:10,default:0,primary,index
	 *
	 * @param mixed $notesId
	 * @return VTigerNotes
	 */
	public function &setNotesId($notesId) {
		$this->notifyChanged(self::FIELD_NOTESID,$this->notesId,$notesId);
		$this->notesId=$notesId;
		return $this;
	}

	/**
	 * get value for notesid 
	 *
	 * type:INT,size:10,default:0,primary,index
	 *
	 * @return mixed
	 */
	public function getNotesId() {
		return $this->notesId;
	}

	/**
	 * set value for note_no 
	 *
	 * type:VARCHAR,size:100,default:null
	 *
	 * @param mixed $noteNo
	 * @return VTigerNotes
	 */
	public function &setNoteNo($noteNo) {
		$this->notifyChanged(self::FIELD_NOTE_NO,$this->noteNo,$noteNo);
		$this->noteNo=$noteNo;
		return $this;
	}

	/**
	 * get value for note_no 
	 *
	 * type:VARCHAR,size:100,default:null
	 *
	 * @return mixed
	 */
	public function getNoteNo() {
		return $this->noteNo;
	}

	/**
	 * set value for title 
	 *
	 * type:VARCHAR,size:50,default:null,index
	 *
	 * @param mixed $title
	 * @return VTigerNotes
	 */
	public function &setTitle($title) {
		$this->notifyChanged(self::FIELD_TITLE,$this->title,$title);
		$this->title=$title;
		return $this;
	}

	/**
	 * get value for title 
	 *
	 * type:VARCHAR,size:50,default:null,index
	 *
	 * @return mixed
	 */
	public function getTitle() {
		return $this->title;
	}

	/**
	 * set value for filename 
	 *
	 * type:VARCHAR,size:200,default:null,nullable
	 *
	 * @param mixed $fileName
	 * @return VTigerNotes
	 */
	public function &setFileName($fileName) {
		$this->notifyChanged(self::FIELD_FILENAME,$this->fileName,$fileName);
		$this->fileName=$fileName;
		return $this;
	}

	/**
	 * get value for filename 
	 *
	 * type:VARCHAR,size:200,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getFileName() {
		return $this->fileName;
	}

	/**
	 * set value for notecontent 
	 *
	 * type:TEXT,size:65535,default:null,nullable
	 *
	 * @param mixed $noteContent
	 * @return VTigerNotes
	 */
	public function &setNoteContent($noteContent) {
		$this->notifyChanged(self::FIELD_NOTECONTENT,$this->noteContent,$noteContent);
		$this->noteContent=$noteContent;
		return $this;
	}

	/**
	 * get value for notecontent 
	 *
	 * type:TEXT,size:65535,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getNoteContent() {
		return $this->noteContent;
	}

	/**
	 * set value for folderid 
	 *
	 * type:INT,size:10,default:1
	 *
	 * @param mixed $folderId
	 * @return VTigerNotes
	 */
	public function &setFolderId($folderId) {
		$this->notifyChanged(self::FIELD_FOLDERID,$this->folderId,$folderId);
		$this->folderId=$folderId;
		return $this;
	}

	/**
	 * get value for folderid 
	 *
	 * type:INT,size:10,default:1
	 *
	 * @return mixed
	 */
	public function getFolderId() {
		return $this->folderId;
	}

	/**
	 * set value for filetype 
	 *
	 * type:VARCHAR,size:50,default:null,nullable
	 *
	 * @param mixed $fileType
	 * @return VTigerNotes
	 */
	public function &setFileType($fileType) {
		$this->notifyChanged(self::FIELD_FILETYPE,$this->fileType,$fileType);
		$this->fileType=$fileType;
		return $this;
	}

	/**
	 * get value for filetype 
	 *
	 * type:VARCHAR,size:50,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getFileType() {
		return $this->fileType;
	}

	/**
	 * set value for filelocationtype 
	 *
	 * type:VARCHAR,size:5,default:null,nullable
	 *
	 * @param mixed $fileLocationType
	 * @return VTigerNotes
	 */
	public function &setFileLocationType($fileLocationType) {
		$this->notifyChanged(self::FIELD_FILELOCATIONTYPE,$this->fileLocationType,$fileLocationType);
		$this->fileLocationType=$fileLocationType;
		return $this;
	}

	/**
	 * get value for filelocationtype 
	 *
	 * type:VARCHAR,size:5,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getFileLocationType() {
		return $this->fileLocationType;
	}

	/**
	 * set value for filedownloadcount 
	 *
	 * type:INT,size:10,default:null,nullable
	 *
	 * @param mixed $fileDownloadCount
	 * @return VTigerNotes
	 */
	public function &setFileDownloadCount($fileDownloadCount) {
		$this->notifyChanged(self::FIELD_FILEDOWNLOADCOUNT,$this->fileDownloadCount,$fileDownloadCount);
		$this->fileDownloadCount=$fileDownloadCount;
		return $this;
	}

	/**
	 * get value for filedownloadcount 
	 *
	 * type:INT,size:10,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getFileDownloadCount() {
		return $this->fileDownloadCount;
	}

	/**
	 * set value for filestatus 
	 *
	 * type:INT,size:10,default:null,nullable
	 *
	 * @param mixed $fileStatus
	 * @return VTigerNotes
	 */
	public function &setFileStatus($fileStatus) {
		$this->notifyChanged(self::FIELD_FILESTATUS,$this->fileStatus,$fileStatus);
		$this->fileStatus=$fileStatus;
		return $this;
	}

	/**
	 * get value for filestatus 
	 *
	 * type:INT,size:10,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getFileStatus() {
		return $this->fileStatus;
	}

	/**
	 * set value for filesize 
	 *
	 * type:INT,size:10,default:0
	 *
	 * @param mixed $filesIze
	 * @return VTigerNotes
	 */
	public function &setFilesIze($filesIze) {
		$this->notifyChanged(self::FIELD_FILESIZE,$this->filesIze,$filesIze);
		$this->filesIze=$filesIze;
		return $this;
	}

	/**
	 * get value for filesize 
	 *
	 * type:INT,size:10,default:0
	 *
	 * @return mixed
	 */
	public function getFilesIze() {
		return $this->filesIze;
	}

	/**
	 * set value for fileversion 
	 *
	 * type:VARCHAR,size:50,default:null,nullable
	 *
	 * @param mixed $fileVersion
	 * @return VTigerNotes
	 */
	public function &setFileVersion($fileVersion) {
		$this->notifyChanged(self::FIELD_FILEVERSION,$this->fileVersion,$fileVersion);
		$this->fileVersion=$fileVersion;
		return $this;
	}

	/**
	 * get value for fileversion 
	 *
	 * type:VARCHAR,size:50,default:null,nullable
	 *
	 * @return mixed
	 */
	public function getFileVersion() {
		return $this->fileVersion;
	}

	/**
	 * Get table name
	 *
	 * @return string
	 */
	public static function getTableName() {
		return self::SQL_TABLE_NAME;
	}

	/**
	 * Get array with field id as index and field name as value
	 *
	 * @return array
	 */
	public static function getFieldNames() {
		return self::$FIELD_NAMES;
	}

	/**
	 * Get array with field id as index and property name as value
	 *
	 * @return array
	 */
	public static function getPropertyNames() {
		return self::$PROPERTY_NAMES;
	}

	/**
	 * get the field name for the passed field id.
	 *
	 * @param int $fieldId
	 * @param bool $fullyQualifiedName true if field name should be qualified by table name
	 * @return string field name for the passed field id, null if the field doesn't exist
	 */
	public static function getFieldNameByFieldId($fieldId, $fullyQualifiedName=true) {
		if (!array_key_exists($fieldId, self::$FIELD_NAMES)) {
			return null;
		}
		$fieldName=self::SQL_IDENTIFIER_QUOTE . self::$FIELD_NAMES[$fieldId] . self::SQL_IDENTIFIER_QUOTE;
		if ($fullyQualifiedName) {
			return self::SQL_IDENTIFIER_QUOTE . self::SQL_TABLE_NAME . self::SQL_IDENTIFIER_QUOTE . '.' . $fieldName;
		}
		return $fieldName;
	}

	/**
	 * Get array with field ids of identifiers
	 *
	 * @return array
	 */
	public static function getIdentifierFields() {
		return self::$PRIMARY_KEYS;
	}

	/**
	 * Get array with field ids of autoincrement fields
	 *
	 * @return array
	 */
	public static function getAutoincrementFields() {
		return self::$AUTOINCREMENT_FIELDS;
	}

	/**
	 * Get array with field id as index and property type as value
	 *
	 * @return array
	 */
	public static function getPropertyTypes() {
		return self::$PROPERTY_TYPES;
	}

	/**
	 * Get array with field id as index and field type as value
	 *
	 * @return array
	 */
	public static function getFieldTypes() {
		return self::$FIELD_TYPES;
	}

	/**
	 * Assign default values according to table
	 * 
	 */
	public function assignDefaultValues() {
		$this->assignByArray(self::$DEFAULT_VALUES);
	}


	/**
	 * return hash with the field name as index and the field value as value.
	 *
	 * @return array
	 */
	public function toHash() {
		$array=$this->toArray();
		$hash=array();
		foreach ($array as $fieldId=>$value) {
			$hash[self::$FIELD_NAMES[$fieldId]]=$value;
		}
		return $hash;
	}

	/**
	 * return array with the field id as index and the field value as value.
	 *
	 * @return array
	 */
	public function toArray() {
		return array(
			self::FIELD_NOTESID=>$this->getNotesId(),
			self::FIELD_NOTE_NO=>$this->getNoteNo(),
			self::FIELD_TITLE=>$this->getTitle(),
			self::FIELD_FILENAME=>$this->getFileName(),
			self::FIELD_NOTECONTENT=>$this->getNoteContent(),
			self::FIELD_FOLDERID=>$this->getFolderId(),
			self::FIELD_FILETYPE=>$this->getFileType(),
			self::FIELD_FILELOCATIONTYPE=>$this->getFileLocationType(),
			self::FIELD_FILEDOWNLOADCOUNT=>$this->getFileDownloadCount(),
			self::FIELD_FILESTATUS=>$this->getFileStatus(),
			self::FIELD_FILESIZE=>$this->getFilesIze(),
			self::FIELD_FILEVERSION=>$this->getFileVersion());
	}


	/**
	 * return array with the field id as index and the field value as value for the identifier fields.
	 *
	 * @return array
	 */
	public function getPrimaryKeyValues() {
		return array(
			self::FIELD_NOTESID=>$this->getNotesId());
	}

	/**
	 * cached statements
	 *
	 * @var array<string,array<string,PDOStatement>>
	 */
	private static $stmts=array();
	private static $cacheStatements=true;
	
	/**
	 * prepare passed string as statement or return cached if enabled and available
	 *
	 * @param PDO $db
	 * @param string $statement
	 * @return PDOStatement
	 */
	protected static function prepareStatement(PDO $db, $statement) {
		if(self::isCacheStatements()) {
			if (in_array($statement, array(self::SQL_INSERT, self::SQL_INSERT_AUTOINCREMENT, self::SQL_UPDATE, self::SQL_SELECT_PK, self::SQL_DELETE_PK))) {
				$dbInstanceId=spl_object_hash($db);
				if (empty(self::$stmts[$statement][$dbInstanceId])) {
					self::$stmts[$statement][$dbInstanceId]=$db->prepare($statement);
				}
				return self::$stmts[$statement][$dbInstanceId];
			}
		}
		return $db->prepare($statement);
	}

	/**
	 * Enable statement cache
	 *
	 * @param bool $cache
	 */
	public static function setCacheStatements($cache) {
		self::$cacheStatements=true==$cache;
	}

	/**
	 * Check if statement cache is enabled
	 *
	 * @return bool
	 */
	public static function isCacheStatements() {
		return self::$cacheStatements;
	}
	
	/**
	 * check if this instance exists in the database
	 *
	 * @param PDO $db
	 * @return bool
	 */
	public function existsInDatabase(PDO $db) {
		$filter=array();
		foreach ($this->getPrimaryKeyValues() as $fieldId=>$value) {
			$filter[]=new DFC($fieldId, $value, DFC::EXACT_NULLSAFE);
		}
		return 0!=count(self::findByFilter($db, $filter, true));
	}
	
	/**
	 * Update to database if exists, otherwise insert
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function updateInsertToDatabase(PDO $db) {
		if ($this->existsInDatabase($db)) {
			return $this->updateToDatabase($db);
		} else {
			return $this->insertIntoDatabase($db);
		}
	}

	/**
	 * Query by Example.
	 *
	 * Match by attributes of passed example instance and return matched rows as an array of VTigerNotes instances
	 *
	 * @param PDO $db a PDO Database instance
	 * @param VTigerNotes $example an example instance defining the conditions. All non-null properties will be considered a constraint, null values will be ignored.
	 * @param boolean $and true if conditions should be and'ed, false if they should be or'ed
	 * @param array $sort array of DSC instances
	 * @return VTigerNotes[]
	 */
	public static function findByExample(PDO $db,VTigerNotes $example, $and=true, $sort=null) {
		$exampleValues=$example->toArray();
		$filter=array();
		foreach ($exampleValues as $fieldId=>$value) {
			if (null!==$value) {
				$filter[$fieldId]=$value;
			}
		}
		return self::findByFilter($db, $filter, $and, $sort);
	}

	/**
	 * Query by filter.
	 *
	 * The filter can be either an hash with the field id as index and the value as filter value,
	 * or a array of DFC instances.
	 *
	 * Will return matched rows as an array of VTigerNotes instances.
	 *
	 * @param PDO $db a PDO Database instance
	 * @param array $filter array of DFC instances defining the conditions
	 * @param boolean $and true if conditions should be and'ed, false if they should be or'ed
	 * @param array $sort array of DSC instances
	 * @return VTigerNotes[]
	 */
	public static function findByFilter(PDO $db, $filter, $and=true, $sort=null) {
		if (!($filter instanceof DFCInterface)) {
			$filter=new DFCAggregate($filter, $and);
		}
		$sql='SELECT * FROM `vtiger_notes`'
		. self::buildSqlWhere($filter, $and, false, true)
		. self::buildSqlOrderBy($sort);

		$stmt=self::prepareStatement($db, $sql);
		self::bindValuesForFilter($stmt, $filter);
		return self::fromStatement($stmt);
	}

	/**
	 * Will execute the passed statement and return the result as an array of VTigerNotes instances
	 *
	 * @param PDOStatement $stmt
	 * @return VTigerNotes[]
	 */
	public static function fromStatement(PDOStatement $stmt) {
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		return self::fromExecutedStatement($stmt);
	}

	/**
	 * returns the result as an array of VTigerNotes instances without executing the passed statement
	 *
	 * @param PDOStatement $stmt
	 * @return VTigerNotes[]
	 */
	public static function fromExecutedStatement(PDOStatement $stmt) {
		$resultInstances=array();
		while($result=$stmt->fetch(PDO::FETCH_ASSOC)) {
			$o=new VTigerNotes();
			$o->assignByHash($result);
			$o->notifyPristine();
			$resultInstances[]=$o;
		}
		$stmt->closeCursor();
		return $resultInstances;
	}

	/**
	 * Get sql WHERE part from filter.
	 *
	 * @param array $filter
	 * @param bool $and
	 * @param bool $fullyQualifiedNames true if field names should be qualified by table name
	 * @param bool $prependWhere true if WHERE should be prepended to conditions
	 * @return string
	 */
	public static function buildSqlWhere($filter, $and, $fullyQualifiedNames=true, $prependWhere=false) {
		if (!($filter instanceof DFCInterface)) {
			$filter=new DFCAggregate($filter, $and);
		}
		return $filter->buildSqlWhere(new self::$CLASS_NAME, $fullyQualifiedNames, $prependWhere);
	}

	/**
	 * get sql ORDER BY part from DSCs
	 *
	 * @param array $sort array of DSC instances
	 * @return string
	 */
	protected static function buildSqlOrderBy($sort) {
		return DSC::buildSqlOrderBy(new self::$CLASS_NAME, $sort);
	}

	/**
	 * bind values from filter to statement
	 *
	 * @param PDOStatement $stmt
	 * @param DFCInterface $filter
	 */
	public static function bindValuesForFilter(PDOStatement &$stmt, DFCInterface $filter) {
		$filter->bindValuesForFilter(new self::$CLASS_NAME, $stmt);
	}

	/**
	 * Execute select query and return matched rows as an array of VTigerNotes instances.
	 *
	 * The query should of course be on the table for this entity class and return all fields.
	 *
	 * @param PDO $db a PDO Database instance
	 * @param string $sql
	 * @return VTigerNotes[]
	 */
	public static function findBySql(PDO $db, $sql) {
		$stmt=$db->query($sql);
		return self::fromExecutedStatement($stmt);
	}

	/**
	 * Delete rows matching the filter
	 *
	 * The filter can be either an hash with the field id as index and the value as filter value,
	 * or a array of DFC instances.
	 *
	 * @param PDO $db
	 * @param array $filter
	 * @param bool $and
	 * @return mixed
	 */
	public static function deleteByFilter(PDO $db, $filter, $and=true) {
		if (!($filter instanceof DFCInterface)) {
			$filter=new DFCAggregate($filter, $and);
		}
		if (0==count($filter)) {
			throw new InvalidArgumentException('refusing to delete without filter'); // just comment out this line if you are brave
		}
		$sql='DELETE FROM `vtiger_notes`'
		. self::buildSqlWhere($filter, $and, false, true);
		$stmt=self::prepareStatement($db, $sql);
		self::bindValuesForFilter($stmt, $filter);
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		return $affected;
	}

	/**
	 * Assign values from array with the field id as index and the value as value
	 *
	 * @param array $array
	 */
	public function assignByArray($array) {
		$result=array();
		foreach ($array as $fieldId=>$value) {
			$result[self::$FIELD_NAMES[$fieldId]]=$value;
		}
		$this->assignByHash($result);
	}

	/**
	 * Assign values from hash where the indexes match the tables field names
	 *
	 * @param array $result
	 */
	public function assignByHash($result) {
		$this->setNotesId($result['notesid']);
		$this->setNoteNo($result['note_no']);
		$this->setTitle($result['title']);
		$this->setFileName($result['filename']);
		$this->setNoteContent($result['notecontent']);
		$this->setFolderId($result['folderid']);
		$this->setFileType($result['filetype']);
		$this->setFileLocationType($result['filelocationtype']);
		$this->setFileDownloadCount($result['filedownloadcount']);
		$this->setFileStatus($result['filestatus']);
		$this->setFilesIze($result['filesize']);
		$this->setFileVersion($result['fileversion']);
	}

	/**
	 * Get element instance by it's primary key(s).
	 * Will return null if no row was matched.
	 *
	 * @param PDO $db
	 * @return VTigerNotes
	 */
	public static function findById(PDO $db,$notesId) {
		$stmt=self::prepareStatement($db,self::SQL_SELECT_PK);
		$stmt->bindValue(1,$notesId);
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$result=$stmt->fetch(PDO::FETCH_ASSOC);
		$stmt->closeCursor();
		if(!$result) {
			return null;
		}
		$o=new VTigerNotes();
		$o->assignByHash($result);
		$o->notifyPristine();
		return $o;
	}

	/**
	 * Bind all values to statement
	 *
	 * @param PDOStatement $stmt
	 */
	protected function bindValues(PDOStatement &$stmt) {
		$stmt->bindValue(1,$this->getNotesId());
		$stmt->bindValue(2,$this->getNoteNo());
		$stmt->bindValue(3,$this->getTitle());
		$stmt->bindValue(4,$this->getFileName());
		$stmt->bindValue(5,$this->getNoteContent());
		$stmt->bindValue(6,$this->getFolderId());
		$stmt->bindValue(7,$this->getFileType());
		$stmt->bindValue(8,$this->getFileLocationType());
		$stmt->bindValue(9,$this->getFileDownloadCount());
		$stmt->bindValue(10,$this->getFileStatus());
		$stmt->bindValue(11,$this->getFilesIze());
		$stmt->bindValue(12,$this->getFileVersion());
	}


	/**
	 * Insert this instance into the database
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function insertIntoDatabase(PDO $db) {
		$stmt=self::prepareStatement($db,self::SQL_INSERT);
		$this->bindValues($stmt);
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		$this->notifyPristine();
		return $affected;
	}


	/**
	 * Update this instance into the database
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function updateToDatabase(PDO $db) {
		$stmt=self::prepareStatement($db,self::SQL_UPDATE);
		$this->bindValues($stmt);
		$stmt->bindValue(13,$this->getNotesId());
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		$this->notifyPristine();
		return $affected;
	}


	/**
	 * Delete this instance from the database
	 *
	 * @param PDO $db
	 * @return mixed
	 */
	public function deleteFromDatabase(PDO $db) {
		$stmt=self::prepareStatement($db,self::SQL_DELETE_PK);
		$stmt->bindValue(1,$this->getNotesId());
		$affected=$stmt->execute();
		if (false===$affected) {
			$stmt->closeCursor();
			throw new Exception($stmt->errorCode() . ':' . var_export($stmt->errorInfo(), true), 0);
		}
		$stmt->closeCursor();
		return $affected;
	}

	/**
	 * Fetch VTigerCRmEntityNotesRel's which this VTigerNotes references.
	 * `vtiger_notes`.`notesid` -> `vtiger_crmentitynotesrel`.`notesid`
	 *
	 * @param PDO $db a PDO Database instance
	 * @param array $sort array of DSC instances
	 * @return VTigerCRmEntityNotesRel[]
	 */
	public function fetchVTigerCRmEntityNotesRelCollection(PDO $db, $sort=null) {
		$filter=array(VTigerCRmEntityNotesRel::FIELD_NOTESID=>$this->getNotesId());
		return VTigerCRmEntityNotesRel::findByFilter($db, $filter, true, $sort);
	}

	/**
	 * Fetch VTigerSeNotesRel's which this VTigerNotes references.
	 * `vtiger_notes`.`notesid` -> `vtiger_senotesrel`.`notesid`
	 *
	 * @param PDO $db a PDO Database instance
	 * @param array $sort array of DSC instances
	 * @return VTigerSeNotesRel[]
	 */
	public function fetchVTigerSeNotesRelCollection(PDO $db, $sort=null) {
		$filter=array(VTigerSeNotesRel::FIELD_NOTESID=>$this->getNotesId());
		return VTigerSeNotesRel::findByFilter($db, $filter, true, $sort);
	}

	/**
	 * Fetch VTigerCRmEntity which references this VTigerNotes. Will return null in case reference is invalid.
	 * `vtiger_notes`.`notesid` -> `vtiger_crmentity`.`crmid`
	 *
	 * @param PDO $db a PDO Database instance
	 * @param array $sort array of DSC instances
	 * @return VTigerCRmEntity
	 */
	public function fetchVTigerCRmEntity(PDO $db, $sort=null) {
		$filter=array(VTigerCRmEntity::FIELD_CRMID=>$this->getNotesId());
		$result=VTigerCRmEntity::findByFilter($db, $filter, true, $sort);
		return empty($result) ? null : $result[0];
	}

	/**
	 * return array with the property name as index and the field value as value.
	 * ezComponents support method
	 *
	 * @return array
	 */
	public function getState() {
		$array=$this->toArray();
		$state=array();
		foreach ($array as $fieldId=>$value) {
			$state[self::$PROPERTY_NAMES[$fieldId]]=$value;
		}
		return $state;
	}

	/**
	 * Assign values from hash where the indexes match the property names.
	 * ezComponents support method
	 *
	 * @param array $state
	 */
	public function setState(array $state) {
		$propertyNameToFieldId=array_flip(self::$PROPERTY_NAMES);
		$hash=$this->toHash();
		foreach ($state as $propertyName=>$value) {
			$hash[self::$FIELD_NAMES[$propertyNameToFieldId[$propertyName]]]=$value;
		}
		$this->assignByHash($hash);
	}

	/**
	 * get persistence definition for ezComponents
	 *
	 * @return ezcPersistentObjectDefinition
	 */
	public static function toEzcPersistentObjectDefinition() {
		static $typeMapping=array(
			Db2PhpEntity::PHP_TYPE_BOOL=>ezcPersistentObjectProperty::PHP_TYPE_BOOL,
			Db2PhpEntity::PHP_TYPE_INT=>ezcPersistentObjectProperty::PHP_TYPE_INT,
			Db2PhpEntity::PHP_TYPE_FLOAT=>ezcPersistentObjectProperty::PHP_TYPE_FLOAT,
			Db2PhpEntity::PHP_TYPE_STRING=>ezcPersistentObjectProperty::PHP_TYPE_STRING
		);
		$def=new ezcPersistentObjectDefinition();
		$def->table=self::SQL_TABLE_NAME;
		$def->class='VTigerNotes';
		if (!empty (self::$PRIMARY_KEYS)) {
			$pkField=self::$PRIMARY_KEYS[0];
			$def->idProperty=new ezcPersistentObjectIdProperty();
			$def->idProperty->columnName=self::$FIELD_NAMES[$pkField];
			$def->idProperty->propertyName=self::$PROPERTY_NAMES[$pkField];
			$def->idProperty->generator=new ezcPersistentGeneratorDefinition(
				in_array($pkField, self::$AUTOINCREMENT_FIELDS) ? 'ezcPersistentNativeGenerator' : 'ezcPersistentManualGenerator');
		} else {
			$pkField=null;
		}
		foreach (self::$PROPERTY_NAMES as $fieldId=>$propertyName) {
			if ($fieldId!==$pkField) {
				$def->properties[$propertyName]=new ezcPersistentObjectProperty();
				$def->properties[$propertyName]->columnName=self::$FIELD_NAMES[$fieldId];
				$def->properties[$propertyName]->propertyName=$propertyName;
				$def->properties[$propertyName]->propertyType=$typeMapping[self::$PROPERTY_TYPES[$fieldId]];
			}
		}
		return $def;
	}


	/**
	 * get element as DOM Document
	 *
	 * @return DOMDocument
	 */
	public function toDOM() {
		return self::hashToDomDocument($this->toHash(), 'VTigerNotes');
	}

	/**
	 * get single VTigerNotes instance from a DOMElement
	 *
	 * @param DOMElement $node
	 * @return VTigerNotes
	 */
	public static function fromDOMElement(DOMElement $node) {
		$o=new VTigerNotes();
		$o->assignByHash(self::domNodeToHash($node, self::$FIELD_NAMES, self::$DEFAULT_VALUES, self::$FIELD_TYPES));
			$o->notifyPristine();
		return $o;
	}

	/**
	 * get all instances of VTigerNotes from the passed DOMDocument
	 *
	 * @param DOMDocument $doc
	 * @return VTigerNotes[]
	 */
	public static function fromDOMDocument(DOMDocument $doc) {
		$instances=array();
		foreach ($doc->getElementsByTagName('VTigerNotes') as $node) {
			$instances[]=self::fromDOMElement($node);
		}
		return $instances;
	}

}
?>